"""edited roleid

Revision ID: 65cf64455a1b
Revises: ae150705e8e3
Create Date: 2024-12-11 17:26:52.399714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65cf64455a1b'
down_revision: Union[str, None] = 'ae150705e8e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('functionalroles', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_functionalroles_id'), 'functionalroles', ['id'], unique=True)
    op.create_unique_constraint(None, 'functionalroles', ['name'])
    op.alter_column('users', 'login',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'fio',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'roleid',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_unique_constraint(None, 'users', ['fio'])
    op.create_unique_constraint(None, 'users', ['login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'roleid',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('users', 'fio',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'login',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'functionalroles', type_='unique')
    op.drop_index(op.f('ix_functionalroles_id'), table_name='functionalroles')
    op.alter_column('functionalroles', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
